# Generated by Django 5.1.6 on 2025-04-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_notification_alter_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookName', models.CharField(max_length=100)),
                ('AuthorName', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
