# Generated by Django 5.1.6 on 2025-04-09 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_books_delete_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='AuthorName',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='BookName',
            new_name='title',
        ),
    ]
