# Generated by Django 5.1.6 on 2025-04-09 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_authorname_books_author_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
