# Generated by Django 5.1.6 on 2025-04-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_books_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='count',
            field=models.BigIntegerField(default=0),
        ),
    ]
