# Generated by Django 5.1.6 on 2025-04-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_book_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='file',
            field=models.FileField(default='default_profile.png', upload_to='books/'),
        ),
    ]
