# Generated by Django 5.1.6 on 2025-04-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_book_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='type',
            field=models.CharField(default='Book Type', max_length=100),
        ),
    ]
