# Generated by Django 5.1.6 on 2025-04-12 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_book_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='count',
        ),
    ]
