# Generated by Django 5.1.6 on 2025-04-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_book_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(default='Book Type', max_length=100)),
                ('file', models.FileField(default='default_profile.png', upload_to='books/')),
            ],
        ),
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(default='Book Type', max_length=100)),
                ('file', models.FileField(default='default_profile.png', upload_to='books/')),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(default='Book Type', max_length=100)),
                ('file', models.FileField(default='default_profile.png', upload_to='books/')),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
    ]
