# Generated by Django 5.1.6 on 2025-04-17 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_logactivities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logactivities',
            name='user',
        ),
    ]
