# Generated by Django 5.1.6 on 2025-04-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_logactivities_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='logactivities',
            name='logoutTime',
            field=models.JSONField(default=list),
        ),
    ]
