# Generated by Django 5.1.6 on 2025-04-18 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_logactivities_logouttime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logactivities',
            old_name='logoutTime',
            new_name='activities',
        ),
        migrations.RemoveField(
            model_name='logactivities',
            name='time',
        ),
    ]
